version: '3.3'
services:
  airflow:  # https://github.com/puckel/docker-airflow
    build:
      context: ..
      dockerfile: ./airflow/Dockerfile
    networks:
      - dsflow
    image: dsflow/airflow
    # restart_policy:
    #   condition: on-failure
    #   delay: 5s
    #   max_attempts: 3
    #   window: 120s
    depends_on:
      - db
    environment:
      LOAD_EX: n
      EXECUTOR: Local
      POSTGRES_HOST: db
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: example
      POSTGRES_DB: airflow
      DSFLOW_ROOT: $DSFLOW_ROOT
      DSFLOW_WORKSPACE: $DSFLOW_WORKSPACE
    volumes:
      - $DSFLOW_ROOT:$DSFLOW_ROOT:ro
      - $DSFLOW_WORKSPACE/jobs:$DSFLOW_WORKSPACE/jobs:ro
      - $DSFLOW_WORKSPACE/airflow/:/root/airflow/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8080"
    # command: webserver

networks:
  dsflow:
    external: true
