version: '3.3'
services:
  dash:  # https://github.com/puckel/docker-airflow
    networks:
      - dsflow
    build:
      context: ..
      dockerfile: ./dash/Dockerfile
    image: dsflow/dash
    # restart_policy:
    #   condition: on-failure
    #   delay: 5s
    #   max_attempts: 3
    #   window: 120s
    volumes:
      - $DSFLOW_WORKSPACE/workflows:/workflows
      - $DSFLOW_WORKSPACE/jobs:/jobs
      - $DSFLOW_WORKSPACE/adhoc:/adhoc
      - $DSFLOW_WORKSPACE/datastore:/data
    ports:
      - 8050:8050
    command: /bin/bash

networks:
  dsflow:
    external: true
