version: '3.3'
services:
  notebook-generator:
    networks:
      - dsflow
    build:
      context: ../..
      dockerfile: ./docker/dsflow-notebook-generator/Dockerfile
    image: dsflow/notebook-generator
    environment:
      DSFLOW_DATASTORE_ROOT: /data
      DSFLOW_JOBS_ROOT: /jobs
      DSFLOW_ROOT: /usr/src/app
    # ports:
    #   - 4040:4040
    #   - 8998:8998
    #   - 8888:8888
    expose:
      - 8998
    volumes:
      - $DSFLOW_WORKSPACE/datastore:/data
      - $DSFLOW_WORKSPACE/jobs:/jobs
      - $DSFLOW_ROOT/dsflow_core=/usr/src/app

networks:
  dsflow:
    external: true
